spring.application.name=cloud-deployment2

server.port=5000

spring.datasource.url=jdbc:mysql://employee-db.cluster-c3omaeaoqrer.ap-southeast-2.rds.amazonaws.com:3306/cloud

spring.datasource.username=admin

spring.datasource.password=Hemanth123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect